#!/bin/bash
# Version 8 (Plasma 6)

packageNamespace=`python3 -c 'import sys, json; print(json.load(sys.stdin).get("KPlugin", {}).get("Id", ""))' < "$PWD/package/metadata.json"`
packageVersion=`python3 -c 'import sys, json; print(json.load(sys.stdin).get("KPlugin", {}).get("Version", ""))' < "$PWD/package/metadata.json"`
plasmoidName="${packageNamespace##*.}" # Strip namespace (Eg: "org.kde.plasma.")
filenameTag="-plasma6"

rm -f ${plasmoidName}-v*.plasmoid
cd package
filename=${plasmoidName}-v${packageVersion}${filenameTag}.plasmoid
zip -r $filename * -x 'translate/*'
mv $filename ../$filename
cd ..
echo "md5: $(md5sum $filename | awk '{ print $1 }')"
echo "sha256: $(sha256sum $filename | awk '{ print $1 }')"
