#!/bin/bash
# Version 6 (Plasma 6)

### Clear SVG cache
rm -f ~/.cache/plasma-svgelements*

killall plasmoidviewer
QML_DISABLE_DISK_CACHE=true plasmoidviewer -a package -l topedge -f horizontal -x 0 -y 0
